// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUC8I5AJbD3tA2RsEvkBkini8RsK7gxmE',
    appId: '1:397051185951:web:1093e4ec04ba478b587e2a',
    messagingSenderId: '397051185951',
    projectId: 'swabi-92720',
    authDomain: 'swabi-92720.firebaseapp.com',
    storageBucket: 'swabi-92720.appspot.com',
    measurementId: 'G-TEX1CR3C1H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUC8I5AJbD3tA2RsEvkBkini8RsK7gxmE',
    appId: '1:397051185951:android:1093e4ec04ba478b587e2a',
    messagingSenderId: '397051185951',
    projectId: 'swabi-92720',
    storageBucket: 'swabi-92720.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcMTE9r5NAMX8GUaUXVhSkyepPswoV9rk',
    appId: '1:397051185951:ios:1093e4ec04ba478b587e2a',
    messagingSenderId: '397051185951',
    projectId: 'swabi-92720',
    storageBucket: 'swabi-92720.appspot.com',
    iosBundleId: 'com.phoenixfx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcMTE9r5NAMX8GUaUXVhSkyepPswoV9rk',
    appId: '1:397051185951:ios:1093e4ec04ba478b587e2a',
    messagingSenderId: '397051185951',
    projectId: 'swabi-92720',
    storageBucket: 'swabi-92720.appspot.com',
    iosBundleId: 'com.example.pheonixfx',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUC8I5AJbD3tA2RsEvkBkini8RsK7gxmE',
    appId: '1:397051185951:web:1093e4ec04ba478b587e2a',
    messagingSenderId: '397051185951',
    projectId: 'swabi-92720',
    authDomain: 'swabi-92720.firebaseapp.com',
    storageBucket: 'swabi-92720.appspot.com',
    measurementId: 'G-D1NEQFBK87',
  );
}
